services:
  dbt:
    build: .
    container_name: curso_dbt_duckdb
    working_dir: /usr/app
    environment:
      - DBT_PROFILES_DIR=/usr/app/profiles
    volumes:
      - ./dbt:/usr/app
    ports:
      - "8080:8080"
    command: tail -f /dev/null

